import {Inter} from "next/font/google";
import "./globals.scss";
import "./typography.scss";
import {Header} from "@/components/header/Header";
import {Footer} from "@/components/footer/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <div className='content-wrapper' >{children}</div>
        <Footer/>
        </body>
        </html>
    );
}
